### ISSUE TITLE
Enhance folder structure

### ISSUE THREAD

**Issue by YousefAldabbas** [igorbenav/FastAPI-boilerplate#43]
Moving schemas inside the version folder could enhance the overall project organization. It might make the versioning more intuitive.
I believe middlewares should be in separate folder that's tell what it contain not like cache middleware its inside `app/core/cache.py`
Also exceptions file should be folder for each "source of error" not sure about the right word for it but for other services/third parties should be in service.py file (as example) inside exceptions folder users as well `UserNotFound` as example

**Comment by igorbenav** [comment]
1. I'll talk more about moving schemas inside the version folder later.
2. About the middleware part, good idea! I'll change it.
3. Could you please elaborate (maybe add examples) for the exceptions part?

Thanks again for the issues, @YousefAldabbas! Appreciated🙌

**Comment by igorbenav** [comment]
Hey, @YousefAldabbas, could you please elaborate for the exceptions part?
 
**About moving schemas inside the version folder:**
It's an option, but I'm also using schemas for **crud**, so crud would also be moved to version folder. See:

```python
# app/core/crud/crud_users.py

from app.crud.crud_base import CRUDBase
from app.models.user import User
from app.schemas.user import UserCreateInternal, UserUpdate, UserUpdateInternal, UserDelete

CRUDUser = CRUDBase[User, UserCreateInternal, UserUpdate, UserUpdateInternal, UserDelete]
crud_users = CRUDUser(User)
```
 
I think it's good creating `schemas` (maybe even `crud`) inside the version folder, but since multiple versions would likely  share at least some schemas, doing this without a shared `schemas` folder would lead to a lot of duplication. 

I think a good alternative would be keeping the folder structure the way it is (with shared `schemas` and `crud` folders) and  if there are multiple versions with different schemas, create a schemas folder also inside the version.

Since in the boilerplate we only have a `v1`, the shared schemas would be enough. Do you agree?

**Comment by igorbenav** [comment]
@YousefAldabbas I'll have to ask you to open a new issue for the exceptions part please.
