### ISSUE TITLE
Enhance logging System

### ISSUE THREAD

**Issue by YousefAldabbas** [igorbenav/FastAPI-boilerplate#44]
logging configurations are on a file but logger object is being declared on each folder you are using it in 
this code from `rate_limit.py` file 
```
from app.core.logger import logging
from app.schemas.rate_limit import sanitize_path

logger = logging.getLogger(__name__)

pool: ConnectionPool | None = None
client: Redis | None = None

logger = logging.getLogger(__name__) # its being declared twice
```
my suggestion will make it easier to use, u will only need to import the logger (object) and use it directly instead of declaring it on each file you want to use it in
`from  app.core import ( logger, ...)`

**Comment by igorbenav** [comment]
Hey, @YousefAldabbas, thanks for sending the issues separately!

- **About the logger being declared twice in `rate_limit.py`:**
Nice catch! Really passed by me, will be fixed!

- **About declaring it once and just importing:**
The logger object is not actually being declared the same throughout the modules, because `__name__` actually gets the module name, so it changes based on where I'm declaring it. This is not necessary, but is usually a good practice to know exactly where the log is coming from, plus it makes different settings based on the module possible.

As you can see in `app/core/logger.py`:
```python
...
LOGGING_LEVEL = logging.INFO
LOGGING_FORMAT = '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
...
```
The `%(name)s` part says the module which the log came from, which is possible because of the declarations in each module with `logger = logging.getLogger(__name__)`. 

So, for a certain module with `__name__` being `myapp.module`, a sample line of the `app.log` file would be:
```
2023-01-01 12:00:00,000 - myapp.module - DEBUG - Starting process
```

Thanks for the issue🎉!
